// <auto-generated />
using System;
using Gymify.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Tempo.Data.Migrations
{
    [DbContext(typeof(TempoDbContext))]
    partial class TempoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gymify.Data.Entities.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeRole")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GymId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HiredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PricePerHour")
                        .HasColumnType("real");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<float>("MembershipFee")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.GymUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GymId")
                        .HasColumnType("int");

                    b.Property<int?>("RegularUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("RegularUserId");

                    b.ToTable("GymUsers");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Notificiation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegularUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RegularUserId");

                    b.ToTable("Notificiations");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.RegularUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RegularUsers");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Employee", b =>
                {
                    b.HasOne("Gymify.Data.Entities.Models.Gym", "Gym")
                        .WithMany("Employees")
                        .HasForeignKey("GymId");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Gym", b =>
                {
                    b.HasOne("Gymify.Data.Entities.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.GymUser", b =>
                {
                    b.HasOne("Gymify.Data.Entities.Models.Gym", "Gym")
                        .WithMany("GymUsers")
                        .HasForeignKey("GymId");

                    b.HasOne("Gymify.Data.Entities.Models.RegularUser", "RegularUser")
                        .WithMany("GymUsers")
                        .HasForeignKey("RegularUserId");

                    b.Navigation("Gym");

                    b.Navigation("RegularUser");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Notificiation", b =>
                {
                    b.HasOne("Gymify.Data.Entities.Models.Admin", "Admin")
                        .WithMany("Notificiations")
                        .HasForeignKey("AdminId");

                    b.HasOne("Gymify.Data.Entities.Models.Employee", "Employee")
                        .WithMany("Notificiations")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Gymify.Data.Entities.Models.RegularUser", "RegularUser")
                        .WithMany("Notificiations")
                        .HasForeignKey("RegularUserId");

                    b.Navigation("Admin");

                    b.Navigation("Employee");

                    b.Navigation("RegularUser");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Admin", b =>
                {
                    b.Navigation("Notificiations");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Employee", b =>
                {
                    b.Navigation("Notificiations");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.Gym", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("GymUsers");
                });

            modelBuilder.Entity("Gymify.Data.Entities.Models.RegularUser", b =>
                {
                    b.Navigation("GymUsers");

                    b.Navigation("Notificiations");
                });
#pragma warning restore 612, 618
        }
    }
}
